feat: add github pages deploy workflow

diff --git a/.github/workflows/production_workflow.yml b/.github/workflows/production_workflow.yml
--- a/.github/workflows/production_workflow.yml
+++ b/.github/workflows/production_workflow.yml
@@ -5,7 +5,7 @@ on:
     branches: [master]
 
 jobs:
-  Build-Project:
+  deploy-on-server:
     environment: production
 
     runs-on: ubuntu-latest
@@ -55,3 +55,38 @@ jobs:
             sudo systemctl restart nginx
             rm -rf dist
           '
+
+  deploy-on-gh-pages:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout source
+        uses: actions/checkout@v4
+
+      - name: Setup Node
+        uses: pnpm/action-setup@v4
+        with:
+          version: 10
+      - run: node -v
+      - run: pnpm -v
+
+      - name: Build project
+        run: |
+          if ! pnpm i --frozen-lockfile; then
+              echo "Install dependencies failed"
+              exit 1
+          fi
+
+          export PUBLIC_API_URL=""
+          if ! pnpm run build; then
+              echo "Build static failed"
+              exit 1
+          fi
+
+      - name: Deploy to GitHub Pages
+        uses: JamesIves/github-pages-deploy-action@v4.4.0
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          folder: dist
+          branch: gh-pages
+          clean: true
+          commit-message: "Deploy to GitHub Pages"
